[theme]
base = "dark"
primaryColor = "#9F7AEA"
backgroundColor = "#1C1C2E"
secondaryBackgroundColor = "#2A2A40"
textColor = "#ECECEC"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false